In [ ]:
import sys
print(sys.executable)

In [6]:
import torch
print(torch.__version__)

2.12.0+cpu


In [11]:
#  creating tensors
import torch
#  1d tensors
x = torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])


In [17]:
#  2d tensors
y = torch.tensor(
    [[1,2],
    [3,4],]
)
print(y)

tensor([[1, 2],
        [3, 4]])


In [19]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [20]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
torch.rand(2,3)

tensor([[0.2069, 0.0234, 0.1971],
        [0.7773, 0.6007, 0.3181]])

In [ ]:
# tensors shape

In [23]:
a = torch.tensor([
    [1,2,3],
    [4,5,6]
])
a.shape

torch.Size([2, 3])

In [27]:
c = torch.tensor([1,2,3])
c[2]

tensor(3)

In [30]:
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(x[(1,1)])
print(x[(1,2)])
print(x[(0,0)])

tensor(5)
tensor(6)
tensor(1)


In [32]:
# operations
c = torch.tensor([1,2,3])
d = torch.tensor([3,2,3])
c*d

tensor([3, 4, 9])

numpy array

In [39]:
import numpy as np 
import torch
arr = np.array([1,2,3])

#  now creating tensors with numpy
n = torch.from_numpy(arr)
print(type(arr))
print(type(n))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [62]:
# project 1
# y = mX + C
import torch
x = torch.tensor([1.,2.,3.])
m = torch.tensor([0.0])
c = torch.tensor([0.0])
y = torch.tensor([3.,1.,2.])

y_pred = m*x + c
print('prediction',y_pred)   # prediction
print('actual',y)   #real
loss = ((y_pred - y) ** 2).mean()

print("Loss:", loss)


prediction tensor([0., 0., 0.])
actual tensor([3., 1., 2.])
Loss: tensor(4.6667)
